const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const {sanitizeEntity}=require('../src/validation');
const context=vm.createContext({state:{realizationYear:'2027'}, normalizeRoute:x=>x});
vm.runInContext(fs.readFileSync('public/years.js','utf8'),context);
assert.equal(vm.runInContext('matchesRealizationYear({realizationYear:"2027",controlYear:"2026"})',context),true);
assert.equal(vm.runInContext('matchesRealizationYear({controlYear:"2027"})',context),false);
context.state.realizationYear='undefined';
assert.equal(vm.runInContext('matchesRealizationYear({})',context),true);
context.state.realizationYear='all';
assert.equal(vm.runInContext('matchesRealizationYear({})',context),true);
assert.equal(sanitizeEntity('proposals',{controlCode:'C 001/2026',realizationYear:'2027'}).realizationYear,'2027');
assert.equal(sanitizeEntity('proposals',{controlCode:'C 001/2026',realizationYear:'',status:'Enviada'}).status,'Enviada');
assert.throws(()=>sanitizeEntity('proposals',{controlCode:'C 001/2026',realizationYear:'2027.5'}));
console.log('Ano independente do controle, filtros e validação: OK');
const storage = new Map();
context.localStorage = { getItem:key=>storage.get(key)||null, setItem:(key,value)=>storage.set(key,value) };
context.state.user = {id:'a'};
context.state.data = {proposals:[{realizationYear:String(new Date().getFullYear())},{realizationYear:'2027'}]};
vm.runInContext('initializeRealizationYear()',context);
assert.equal(context.state.realizationYear,String(new Date().getFullYear()));
storage.set('saesp:realization-year:a','2027');
context.state.yearPreferenceKey = null;
vm.runInContext('initializeRealizationYear()',context);
assert.equal(context.state.realizationYear,'2027');
context.state.user = {id:'b'};
vm.runInContext('initializeRealizationYear()',context);
assert.equal(context.state.realizationYear,String(new Date().getFullYear()));
context.state.realizationYear='2027';
assert.equal(vm.runInContext('kanbanYearBadge({realizationYear:"2027"})',context),'');
assert.match(vm.runInContext('kanbanYearBadge({})',context),/year-badge-undefined/);
console.log('Primeiro acesso, persistência por usuário e badges: OK');
context.state.data = {proposals:[{realizationYear:'2026'},{realizationYear:'2027'},{realizationYear:'2026'},{}]};
assert.equal(vm.runInContext('availableRealizationYears().join(",")',context),'2027,2026');
context.state.realizationYear='2029';
vm.runInContext('initializeRealizationYear()',context);
assert.ok(['2026','2027'].includes(context.state.realizationYear));
context.state.data.proposals=[];
vm.runInContext('initializeRealizationYear()',context);
assert.equal(context.state.realizationYear,'all');
console.log('Somente anos cadastrados e recuperação de seleção removida: OK');
